Extractor Catalog generic search filter / matching ANY/ALL
clowder-framework/clowder pull request #120
Opened 2020-10-27 15:40 UTC by bodom0015

## Description

### Problem
Design includes more ways to filter catalog results than we currently offer.

### Approach
Add generic search filter to the Extractor Catalog, match ALL/ANY, and make sure these filters play nicely with the label filter.

### How to Test
Prerequisites: RabbitMQ plugin enabled, at least two different types of extractors registered

1. Checkout and run this branch locally
2. Login to Clowder
3. Navigate to the Extractor Catalog
    * You should see a text input allowing for a general text search (e.g. name, authors, description, etc)
    * You should see radio buttons offering to "match ANY" or "match ALL"
4. Enter a nonsensical combination, for example: `Match ALL` and a general text search of `asdf`
    * You should see no results
5. Choose a label (e.g. Image), `Match ALL`, and general search of "Rob Kooper"
    * You should see only image-based extractors that include "Rob Kooper" as a contributor or author

NOTE: If a Label is selected, then we calculate its intersect with the results of the other filters regardless of whether "match ANY" / "match ALL" is selected. This is to avoid the case where the user chooses "Image" explicitly, where "match ANY" will can non-image results to that list.

## Review Time Estimate

- [ ] Immediately
- [x] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-10-29 16:02 UTC, lmarini requested changes
I played around with different options and it looks like everything is working as intended. I really like that you are using the metadata definitions in the context for populating the metadata list. It's not something that we are good at keeping documented, but this is a great use for it.

The only thing that I would change is default listing. Right now it seems like it doesn't show anything by default when you open up the page. I would expect it to show all of the extractors and then the user could filter down the list using the controls. I am not sure a user would know what to filter on the first time they load this page. Similar to what we do for labels.

2020-10-29 21:18 UTC, bodom0015 commented
Good catch! I made a commit to address this case.

The ALL + no filters case works because it starts with the full list and trims it down. ANY + no filters does not work in the same way because we start with an empty list and build it up.

More details:
The set theory works out well for the `ALL` case when no filters are entered. For ANY, things get a little weird if you don't specify one or more of the filters: blindly returning the full list in an ANY query would always return the full list, so we return an empty list for that case's default instead. This is why the `defaultValue` stuff was needed in this PR: intersect needs to be inclusive and union needs to be exclusive.

2020-10-30 20:00 UTC, max-zilla commented
Everything worked well for me! Also changing this to be against the Release branch.

2020-10-30 20:01 UTC, max-zilla approved these changes

2020-11-02 15:49 UTC, lmarini approved these changes

2020-11-02 15:49 UTC, merged