Metadata tab select
clowder-framework/clowder pull request #126
Opened 2020-11-02 20:20 UTC by MBcode

## Description

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-11-02 20:21 UTC, MBcode commented
When there are no files on dataset page, select metadata tab instead.

2020-11-09 21:29 UTC, MBcode commented
I was looking through the dataset templating file(app/views/dataset.scala.html line256)& noticed:  
@* FIXME Commented out since it creates some issues with dataset previewers *@
  @<script src=“@routes.Assets.at(“javascripts/tabsInURL.js”)” type=“text/javascript”></script>@
So (maybe) we should coordinate on the hash part of this (later)?

2020-11-11 19:13 UTC, MBcode commented
tabsInURL.js will take/set hash's from/to the URL. logic is working for setting active, but this js won't do the set-active part alone

2020-11-13 17:50 UTC, MBcode commented
the hash-url fixme warning probably should be better tested, but still want to get in the tab switching to metadata (when there, &no files).  Nice to get in soon, as external search is now directing these dataset pages, to see the metadata('details')

2020-11-18 17:33 UTC, MBcode commented
Not easy to test the hash-url part w/geoserver right now; So anyone is welcome to try out the split-out tab-switching (I'll make this active for review)

2020-12-02 16:26 UTC, lmarini requested changes
We need to test if the dataset geospatial layers is affected by this. It wasn't the reason why this was turned off, but it is another previewer where the issue can happen.

2020-12-02 16:26 UTC, lmarini commented on app/views/dataset.scala.html
> +										@if(dataset.files.isEmpty && (m.size > 0)) {
Indentation is off. Thanks!

2022-02-15 22:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/clowder-framework/clowder?pullRequest=126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/clowder-framework/clowder?pullRequest=126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/clowder-framework/clowder?pullRequest=126) it.</sub>

2022-06-14 17:54 UTC, lmarini requested changes
When pulling up the page with no files and some metadata, the tab/name is selected but the body still points to the file tab

<img width="782" alt="Screen Shot 2022-06-14 at 12 54 14 PM" src="https://user-images.githubusercontent.com/599725/173656879-f870d0c8-d560-473a-b75e-3663535a4ab6.png">
.

2022-06-24 21:50 UTC, MBcode commented on app/views/dataset.scala.html
> +										@if(dataset.files.isEmpty && (m.size > 0)) {
tabs v spaces; fixed

2022-06-28 19:22 UTC, MBcode commented
Same logic used to make "tab-pane fade in active" along with with the tab having class="active"

2022-08-29 21:55 UTC, lmarini requested changes
Please updated changelog. Otherwise good to go. Thank you.

2022-09-06 18:20 UTC, lmarini approved these changes

2022-09-06 18:20 UTC, merged