rewrite getting started docs to be friendly to all new users
clowder-framework/clowder pull request #298
Opened 2021-10-21 04:28 UTC by KastanDay

## Description

I updated a single page of the the Sphinx documentation (`administration` -> `getting started`) to make it far easier for new users to get started (including no-install users, Clowder developers and production instances of Clowder). The updated instructions provide step-by-step information, solving all the problems and missing little details I had when first building Clowder from source.

After several rounds of edits, I think the documentation will be very actionable for any user regardless of technical experience.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

Documentation update for 'getting started' for new users. No information removed, only updated.

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
  - I have NOT updated the Changelog for this documentation update.
- [x] I have signed the CLA
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

2021-10-31 00:42 UTC, KastanDay commented on doc/src/sphinx/userguide/installing_clowder.rst
> +   ``docker-compose -f docker-compose.override.yml up -d``
Wonderful, thank you for clarifying. In my latest commit I have updated all docs and paraphrased your note:

> By default, running ``docker-compose up -d`` uses the ``docker-compose.yml`` configuration and will apply overrides found in ``docker-compose.override.yml``. Neither file need to be specified on the command line.

2021-11-09 18:42 UTC, lmarini requested changes
Some quick suggestions otherwise it looks great. Thanks!

2021-11-09 18:42 UTC, lmarini commented on doc/src/sphinx/userguide/installing_clowder.rst
> +2. Download and unzip the `latest stable version here <Download and unzip a specific version: Latest stable version.>`_
If they are using docker compose they don't need to download the build. They can just get the docker-compose files from the github repository https://github.com/clowder-framework/clowder. The could clone the whole thing or download it as a zip file.

2021-11-09 18:42 UTC, lmarini commented on doc/src/sphinx/userguide/installing_clowder.rst
> +   wget -O docker-compose.yml https://opensource.ncsa.illinois.edu/bitbucket/projects/CATS/repos/clowder/raw/docker-compose.yml\?at\=refs%2Fheads%2Fdevelop
The latest one is available on github https://raw.githubusercontent.com/clowder-framework/clowder/develop/docker-compose.yml. There is also a few other override files there that are helpful. Maybe mention that as well. In fact, they might as well clone/download the repository.

2021-11-09 18:42 UTC, lmarini commented on doc/src/sphinx/userguide/installing_clowder.rst
> +-  See `Kubernetes install instructions here <https://opensource.ncsa.illinois.edu/confluence/display/CATS/Kubernetes>`__
Let's point them to https://github.com/clowder-framework/clowder-helm instead. It will contain the most recent information.

2021-11-09 18:42 UTC, lmarini commented on doc/src/sphinx/userguide/installing_clowder.rst
> +in MongoDB**. You can skip this step if haven’t created a local Clowder
You can skip this step if *you* haven’t created

2021-11-10 22:00 UTC, closed without merging

2021-11-19 21:52 UTC, KastanDay commented
request to reopen