Support private extractor registration
clowder-framework/clowder pull request #300
Opened 2021-10-22 15:58 UTC by max-zilla

Adds support for a unique_key and owner parameter to register extractors for personal use. Links to come for related pyclowder and extractor code.

2022-02-15 22:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/clowder-framework/clowder?pullRequest=300) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/clowder-framework/clowder?pullRequest=300) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/clowder-framework/clowder?pullRequest=300) it.</sub>

2022-08-17 15:45 UTC, robkooper reviewed
LGTM, need to do testing

2022-08-17 15:45 UTC, robkooper commented on app/services/mongodb/MongoDBExtractorService.scala
> +        val category_match = doc.categories.length == 0 || doc.categories.intersect(upper_categories).length > 0
was this a bug?

2022-08-25 18:42 UTC, ddey2 approved these changes
I tested it.Looks good to me

2022-08-29 19:18 UTC, lmarini requested changes
Max is adding checks to api.Extractions.submitFileToExtractor and api.Extractions.submitDatasetToExtractor

2022-09-07 03:31 UTC, robkooper commented
not sure why the checks are not running, but on my local machine I get compile errors:

```
[error] /Users/kooper/git/clowder/clowder/app/controllers/Extractors.scala:44: not enough arguments for method getExtractorInfo: (extractorName: String, extractorKey: Option[String], user: Option[models.User])Option[models.ExtractorInfo].
[error] Unspecified value parameter user.
[error]     extractorService.getExtractorInfo(extractorName, extractor_key) match {
[error]                                      ^
```

```
[error] /Users/kooper/git/clowder/clowder/app/api/Extractions.scala:383: not enough arguments for method getExtractorInfo: (extractorName: String, extractorKey: Option[String], user: Option[models.User])Option[models.ExtractorInfo].
[error] Unspecified value parameter user.
[error]     extractors.getExtractorInfo(extractorName, extractor_key) match {
[error]                                ^
[error] /Users/kooper/git/clowder/clowder/app/api/Extractions.scala:525: not enough arguments for method getExtractorInfo: (extractorName: String, extractorKey: Option[String], user: Option[models.User])Option[models.ExtractorInfo].
[error] Unspecified value parameters extractorName, extractorKey, user.
[error]               extractors.getExtractorInfo()
[error]                                          ^
```

```
[error] /Users/kooper/git/clowder/clowder/app/services/ExtractorRoutingService.scala:79: not enough arguments for method getExtractorInfo: (extractorName: String, extractorKey: Option[String], user: Option[models.User])Option[models.ExtractorInfo].
[error] Unspecified value parameter user.
[error]       extractorsService.getExtractorInfo(exId, None)).filter(exInfo => {
[error]                                         ^
```

2022-12-09 21:49 UTC, ddey2 approved these changes

2022-12-14 20:29 UTC, merged