Added Google's model viewer within viewer_three.js
clowder-framework/clowder pull request #372
Opened 2022-08-13 12:53 UTC by cconsta1

## Description

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ X] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ X] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-13 12:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/clowder-framework/clowder?pullRequest=372) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/clowder-framework/clowder?pullRequest=372) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: cconsta1<br/>:white_check_mark: lmarini<br/>:x: Chrysovalantis Constantinou<br/><hr/>**Chrysovalantis Constantinou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/clowder-framework/clowder?pullRequest=372) it.</sub>

2022-08-13 12:55 UTC, cconsta1 commented
Hi! To test the changes please use the attached file containing 3D models :)
[models.zip](https://github.com/clowder-framework/clowder/files/9331470/models.zip)

2022-08-27 13:07 UTC, cconsta1 reviewed
I think I must have removed the console.log

2022-08-27 13:08 UTC, cconsta1 commented on public/javascripts/previewers/three_js/viewer_three.js
> +console.log("This is the 3D viewer");
Hi @robkooper, I think I must have removed the `console.log`. Sorry, I was using it for testing the previewer and forgot to remove it. Please let me know if everything is ok now. Thanks!

2022-08-27 14:53 UTC, robkooper commented on public/javascripts/previewers/three_js/viewer_three.js
> +console.log("This is the 3D viewer");
no worries, i do the same and sometimes leave them. @lmarini will look at this on Monday, and I expect it to get included in the release later that day.

2022-08-27 17:41 UTC, cconsta1 commented on public/javascripts/previewers/three_js/viewer_three.js
> +console.log("This is the 3D viewer");
@robkooper thank you very much, this sounds great!!

2022-08-29 20:47 UTC, lmarini requested changes
I noticed that when viewing .glb files the viewerport is much smaller than when viewing .fbx. Is that intentional?

Testing on firefox and chrome on mac. Otherwise it works great!

![Screen Shot 2022-08-29 at 3 43 29 PM](https://user-images.githubusercontent.com/599725/187295926-b0b25839-6fd4-49fe-9e03-5db07b4d071d.png)

![Screen Shot 2022-08-29 at 3 43 17 PM](https://user-images.githubusercontent.com/599725/187295957-8a2b9e95-3c84-4d12-abed-1279e15e6adb.png)

2022-08-29 21:48 UTC, cconsta1 commented
Hi Luigi,

Maybe this has something to do with the fact that I now used Google’s model viewer to load the GLB files instead of the three.js library (which I used before). But no it’s not intentional. I can check tomorrow. However, I did notice the viewport getting huge, which happens when I load 3D models with the developer tools open. I don’t know why that happens to be honest. To reproduce this, please load a file with the tools open and once it loads close the dev tools. 

Best regards,
Valentino 


Sent from my iPhone

> On Aug 29, 2022, at 11:48 PM, Luigi Marini ***@***.***> wrote:
> 
> ﻿
> @lmarini requested changes on this pull request.
> 
> I noticed that when viewing .glb files the viewerport is much smaller than when viewing .fbx. Is that intentional?
> 
> Testing on firefox and chrome on mac.
> 
> 
> 
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

2022-08-29 22:00 UTC, lmarini commented
> Hi Luigi, Maybe this has something to do with the fact that I now used Google’s model viewer to load the GLB files instead of the three.js library (which I used before). But no it’s not intentional. I can check tomorrow. However, I did notice the viewport getting huge, which happens when I load 3D models with the developer tools open. I don’t know why that happens to be honest. To reproduce this, please load a file with the tools open and once it loads close the dev tools. Best regards, Valentino
> […](#)
> Sent from my iPhone
> On Aug 29, 2022, at 11:48 PM, Luigi Marini ***@***.***> wrote: ﻿ @lmarini requested changes on this pull request. I noticed that when viewing .glb files the viewerport is much smaller than when viewing .fbx. Is that intentional? Testing on firefox and chrome on mac. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

@cconsta1 I tried with developer tools open on both firefox and chrome but the same thing happens.

2022-08-29 22:17 UTC, cconsta1 commented
Hi Luigi,

I think I know what the problem might be. The GLB file loads using the
element <model-viewer>. On my first try, the viewport was as small as yours
in the picture but I remedied that by adding a CSS entry:

model-viewer {
width: 640px;
height: 480px;
}

The CSS file (style.css) loads inside the viewer_three.js file. Somehow,
it's not working on your side. I can check tomorrow. I'm attaching what I'm
seeing on my side.

Regards,
Valentino


On Tue, Aug 30, 2022 at 1:00 AM Luigi Marini ***@***.***>
wrote:

> Hi Luigi, Maybe this has something to do with the fact that I now used
> Google’s model viewer to load the GLB files instead of the three.js library
> (which I used before). But no it’s not intentional. I can check tomorrow.
> However, I did notice the viewport getting huge, which happens when I load
> 3D models with the developer tools open. I don’t know why that happens to
> be honest. To reproduce this, please load a file with the tools open and
> once it loads close the dev tools. Best regards, Valentino
> … <#m_-7621028661472024347_>
> Sent from my iPhone
> On Aug 29, 2022, at 11:48 PM, Luigi Marini *@*.***> wrote: ﻿ @lmarini
> <https://github.com/lmarini> requested changes on this pull request. I
> noticed that when viewing .glb files the viewerport is much smaller than
> when viewing .fbx. Is that intentional? Testing on firefox and chrome on
> mac. — Reply to this email directly, view it on GitHub, or unsubscribe. You
> are receiving this because you authored the thread.
>
> @cconsta1 <https://github.com/cconsta1> I tried with developer tools open
> on both firefox and chrome but the same thing happens.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/clowder-framework/clowder/pull/372#issuecomment-1230907876>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ3IKS7FPYYDECD5GT4DOH3V3UXJNANCNFSM56ODJLIA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-30 15:11 UTC, lmarini commented
Thank you, Valentino. So you have the same problem, but adding the model-viewer style at run time fixes it? Do you always have to add it after you refresh the page?

Thank you,
Luigi

From: Chrysovalantis Constantinou ***@***.***>
Date: Monday, August 29, 2022 at 5:17 PM
To: clowder-framework/clowder ***@***.***>
Cc: Marini, Luigi ***@***.***>, Mention ***@***.***>
Subject: Re: [clowder-framework/clowder] Added Google's model viewer within viewer_three.js (PR #372)
Hi Luigi,

I think I know what the problem might be. The GLB file loads using the
element <model-viewer>. On my first try, the viewport was as small as yours
in the picture but I remedied that by adding a CSS entry:

model-viewer {
width: 640px;
height: 480px;
}

The CSS file (style.css) loads inside the viewer_three.js file. Somehow,
it's not working on your side. I can check tomorrow. I'm attaching what I'm
seeing on my side.

Regards,
Valentino


On Tue, Aug 30, 2022 at 1:00 AM Luigi Marini ***@***.***>
wrote:

> Hi Luigi, Maybe this has something to do with the fact that I now used
> Google’s model viewer to load the GLB files instead of the three.js library
> (which I used before). But no it’s not intentional. I can check tomorrow.
> However, I did notice the viewport getting huge, which happens when I load
> 3D models with the developer tools open. I don’t know why that happens to
> be honest. To reproduce this, please load a file with the tools open and
> once it loads close the dev tools. Best regards, Valentino
> … <#m_-7621028661472024347_>
> Sent from my iPhone
> On Aug 29, 2022, at 11:48 PM, Luigi Marini *@*.***> wrote: ﻿ @lmarini
> <https://github.com/lmarini><https://urldefense.com/v3/__https:/github.com/lmarini*3E__;JQ!!DZ3fjg!5bEmi9TDZ7MxLva6Ak3GtRPsz7F-u1uKHY7wkO-FN9LZuRc4pTI6xd8kehUhOtdsUJGWzA079UwntnxNwDKxwJz6Uw$> requested changes on this pull request. I
> noticed that when viewing .glb files the viewerport is much smaller than
> when viewing .fbx. Is that intentional? Testing on firefox and chrome on
> mac. — Reply to this email directly, view it on GitHub, or unsubscribe. You
> are receiving this because you authored the thread.
>
> @cconsta1 <https://github.com/cconsta1><https://urldefense.com/v3/__https:/github.com/cconsta1*3E__;JQ!!DZ3fjg!5bEmi9TDZ7MxLva6Ak3GtRPsz7F-u1uKHY7wkO-FN9LZuRc4pTI6xd8kehUhOtdsUJGWzA079UwntnxNwDKy_kXjYA$> I tried with developer tools open
> on both firefox and chrome but the same thing happens.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/clowder-framework/clowder/pull/372#issuecomment-1230907876><https://urldefense.com/v3/__https:/github.com/clowder-framework/clowder/pull/372*issuecomment-1230907876*3E__;IyU!!DZ3fjg!5bEmi9TDZ7MxLva6Ak3GtRPsz7F-u1uKHY7wkO-FN9LZuRc4pTI6xd8kehUhOtdsUJGWzA079UwntnxNwDIDdxqp5w$>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJ3IKS7FPYYDECD5GT4DOH3V3UXJNANCNFSM56ODJLIA><https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AJ3IKS7FPYYDECD5GT4DOH3V3UXJNANCNFSM56ODJLIA*3E__;JQ!!DZ3fjg!5bEmi9TDZ7MxLva6Ak3GtRPsz7F-u1uKHY7wkO-FN9LZuRc4pTI6xd8kehUhOtdsUJGWzA079UwntnxNwDI1UqVq3g$>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/clowder-framework/clowder/pull/372*issuecomment-1230926749__;Iw!!DZ3fjg!5bEmi9TDZ7MxLva6Ak3GtRPsz7F-u1uKHY7wkO-FN9LZuRc4pTI6xd8kehUhOtdsUJGWzA079UwntnxNwDJUPfQwcQ$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AAESNLJNFJK6UEX6SBM6HD3V3UZI5ANCNFSM56ODJLIA__;!!DZ3fjg!5bEmi9TDZ7MxLva6Ak3GtRPsz7F-u1uKHY7wkO-FN9LZuRc4pTI6xd8kehUhOtdsUJGWzA079UwntnxNwDIMAOdu0w$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-01-17 20:03 UTC, cconsta1 commented
Hi! I think I never answered this! What do you mean by loading the CSS style at run time?

2023-09-12 15:43 UTC, lmarini approved these changes

2023-09-12 15:43 UTC, merged