Fix to remove a dataset from a space #349
clowder-framework/clowder pull request #373
Opened 2022-08-15 20:30 UTC by ddey2

Signed-off-by: Dipannita Dey <ddey2@illinois.edu>

## Description

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have signed the CLA
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-08-15 21:03 UTC, robkooper commented on app/services/mongodb/MongoDBSpaceService.scala
> +    log.info(s"Space Service - removing $dataset from $space")
can this be debug again?

2022-08-15 21:04 UTC, robkooper commented
can you update the CHANGELOG, and add a line that due to this bug, counts might be off and users should run the fixcounts script

2022-08-15 21:04 UTC, robkooper requested changes
- changelog
- info -> debug

2022-08-15 21:07 UTC, ddey2 commented on app/services/mongodb/MongoDBSpaceService.scala
> +    log.info(s"Space Service - removing $dataset from $space")
My apology. Fixed.

2022-08-15 21:38 UTC, longshuicy approved these changes

2022-08-17 16:10 UTC, ddey2 commented
> * changelog
> * info -> debug

Done

2022-08-17 16:15 UTC, robkooper approved these changes

2022-08-24 03:29 UTC, merged