Fix profile xss
clowder-framework/clowder pull request #449
Opened 2024-04-28 20:42 UTC by tcnichol

you can change the firstName and lastName to include javascript using the endpoint:

`localhost:9002/api/users/662eacbe89108d20fb4cab22/updateName?firstName=bb&lastName=<script>alert('XSS')</script>`

I am using an imported function. This gets rid of the javascript being called, but then the name is blank on the profile page. It may not be the right method for this.

2024-04-29 22:02 UTC, longshuicy commented
@lmarini and I looked together on other possible places related to this bug and realize that sometime it's unnecessary for the frontend template to use @Html(). It should just render it as plain text instead of as html tags.

- The only exception I can think of is Customize the "welcome" page. 
- Maybe even for the places that needs "html" tag, we can exclude <script> tag

e.g.
https://github.com/search?q=repo%3Aclowder-framework%2Fclowder+%40html&type=code&p=1

2024-05-02 20:31 UTC, tcnichol commented
Replacing 

`@Html(profile.lastName)`

with 

`(profile.lastName)`

still calls the javascript function.

I am going to try writing an escape function that we can use.

2024-05-21 18:21 UTC, longshuicy requested changes

2024-05-21 18:21 UTC, longshuicy commented on app/api/Datasets.scala
> +        foldersContainingFile.foreach(folder => {
Any reason this logic is needed here?

2024-05-21 18:21 UTC, longshuicy commented on app/views/profile.scala.html
> +                        <h1 id="first-name-title" class="inline" style="cursor:pointer" title="Click to edit user's first name.">@Html(escapeString("<script>alert('XSS')</script>"))</h1>
What happen if you just remove the @Html() altogether? Like we discussed, this way no html tag should be executed

2024-05-21 18:21 UTC, longshuicy commented on app/views/profile.scala.html
> +                        <h1 id="first-name-title" class="inline" style="cursor:pointer" title="Click to edit user's first name.">@Html(escapeString("<script>alert('XSS')</script>"))</h1>
Also shouldn't this be profile.firstName still? Looks like you might've pushed an temporary test to this PR.

2024-05-21 18:21 UTC, longshuicy commented on app/views/profile.scala.html
> +                        <h1 id="first-name-title" class="inline" style="cursor:pointer" title="Click to edit user's first name.">@Html(escapeString("<script>alert('XSS')</script>"))</h1>
Last thing, there might be other places with @Html tag, could you also apply the same fix to those?

2024-05-21 18:21 UTC, longshuicy commented on docker-compose.yml
> +    image: clowder:bugfix
Again this looks like a temp commit, should it revert back to the original image?

2025-07-28 16:19 UTC, lmarini commented
Fixed https://github.com/clowder-framework/clowder/pull/459

2025-07-28 16:19 UTC, closed without merging