Extractor Catalog - enable trigger filter to separate file/dataset extractors
clowder-framework/clowder pull request #80
Opened 2020-09-25 18:03 UTC by max-zilla

This adds a small bit of logic to the /extractors endpoint that will filter by extractor trigger if file/* or dataset/* is selected. In full implementation this should have dynamic autocomplete or at least a list generated from found records, but as a proof-of-concept here is minimum example.

2020-09-29 18:27 UTC, lmarini commented
Needs changelog.

2020-09-29 18:32 UTC, lmarini requested changes
I don't know if this needs to be address in this PR, but if I select a filter for which I have no extractors matching, the page will show blank with a "No extractors running" message. This was ok before when the list of extractors represented that, but it's confusing now that we filter down. Should we show the regular page with no extractors in the table?

2020-09-30 13:16 UTC, max-zilla commented
> I don't know if this needs to be address in this PR, but if I select a filter for which I have no extractors matching, the page will show blank with a "No extractors running" message. This was ok before when the list of extractors represented that, but it's confusing now that we filter down. Should we show the regular page with no extractors in the table?

I noticed that with metadata filter as well. Probably better to show the regular page with no extractors once a filter is chosen, will see if i can modify.

2020-09-30 13:17 UTC, max-zilla commented
> Needs changelog.

this is into Mike's branch/PR, not develop. i think that changelog will cover everything

2020-09-30 17:13 UTC, bodom0015 approved these changes
LGTM, aside from hitting the same "No extractors running" issue as mentioned above.

Works as advertised :+1:

2020-10-01 13:54 UTC, max-zilla commented
OK, I simply removed the "No extractors found" page and we'll always show the list. I re-added the metadata filter to demonstrate this as many instances will not have any, but it isn't as disruptive now. If the instance truly has no extractors running, they'll see an empty list with filter controls. (commit looks larger than it is due to it being mostly a large de-dent of the indent level)

2020-10-05 15:30 UTC, merged